wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1653693149
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      4: 3.8.12
      5: 0.12.17
      8:
      - 5
